apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - config.yaml
  - management.yaml
  - api.yaml
images:
  - name: configra
    newName: registry.example.com/configra
    newTag: v1.1.0
