-- Apply to a dedicated Configra database after reviewing its name.
-- Roles have no passwords. Assign each role to a separately provisioned account,
-- restrict connection hosts, and SET DEFAULT ROLE for that account.
-- This script only adds grants; review existing accounts/roles for excess grants.
CREATE ROLE IF NOT EXISTS 'configra_api';
CREATE ROLE IF NOT EXISTS 'configra_management';
CREATE ROLE IF NOT EXISTS 'configra_backup';
CREATE ROLE IF NOT EXISTS 'configra_doctor';
CREATE ROLE IF NOT EXISTS 'configra_gc';
GRANT SELECT ON `configra`.`schema_migrations` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`crypto_sentinel` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`environments` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`configs` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`config_env_states` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`config_revisions` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`config_revision_vault_refs` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`vault_items` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`vault_fields` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`vault_item_revisions` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`vault_revision_fields` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`vault_revision_variants` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`vault_revision_variant_environments` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`api_tokens` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`api_token_environments` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`client_certificates` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`certificate_authorities` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`operations` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`outbox_events` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`notification_destinations` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`notification_subscriptions` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`config_release_sets` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.`config_release_states` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`configs` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`config_env_states` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`config_revisions` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`config_revision_vault_refs` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`vault_items` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`vault_fields` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`vault_item_revisions` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`vault_revision_fields` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`vault_revision_variants` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`vault_revision_variant_environments` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`api_tokens` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`api_token_environments` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`client_certificates` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`operations` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`outbox_events` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`notification_targets` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`config_release_sets` TO 'configra_api', 'configra_management';
GRANT INSERT ON `configra`.`config_release_states` TO 'configra_api', 'configra_management';
GRANT UPDATE ON `configra`.`configs` TO 'configra_api', 'configra_management';
GRANT UPDATE ON `configra`.`config_env_states` TO 'configra_api', 'configra_management';
GRANT UPDATE ON `configra`.`vault_items` TO 'configra_api', 'configra_management';
GRANT UPDATE ON `configra`.`vault_fields` TO 'configra_api', 'configra_management';
GRANT UPDATE ON `configra`.`api_tokens` TO 'configra_api', 'configra_management';
GRANT UPDATE ON `configra`.`client_certificates` TO 'configra_api', 'configra_management';
GRANT UPDATE ON `configra`.`operations` TO 'configra_api', 'configra_management';
GRANT UPDATE ON `configra`.`certificate_authorities` TO 'configra_api', 'configra_management';
GRANT UPDATE ON `configra`.`config_release_sets` TO 'configra_api', 'configra_management';
GRANT UPDATE ON `configra`.`config_release_states` TO 'configra_api', 'configra_management';
GRANT SELECT ON `configra`.* TO 'configra_management';
GRANT INSERT ON `configra`.`environments` TO 'configra_management';
GRANT INSERT ON `configra`.`certificate_authorities` TO 'configra_management';
GRANT INSERT ON `configra`.`notification_destinations` TO 'configra_management';
GRANT INSERT ON `configra`.`notification_subscriptions` TO 'configra_management';
GRANT INSERT ON `configra`.`notification_deliveries` TO 'configra_management';
GRANT INSERT ON `configra`.`management_sessions` TO 'configra_management';
GRANT INSERT ON `configra`.`management_session_policies` TO 'configra_management';
GRANT UPDATE ON `configra`.`environments` TO 'configra_management';
GRANT UPDATE ON `configra`.`notification_destinations` TO 'configra_management';
GRANT UPDATE ON `configra`.`notification_targets` TO 'configra_management';
GRANT UPDATE ON `configra`.`outbox_events` TO 'configra_management';
GRANT UPDATE ON `configra`.`management_sessions` TO 'configra_management';
GRANT UPDATE ON `configra`.`management_session_policies` TO 'configra_management';
GRANT DELETE ON `configra`.`api_token_environments` TO 'configra_management';
GRANT DELETE ON `configra`.`notification_subscriptions` TO 'configra_management';
GRANT DELETE ON `configra`.`management_sessions` TO 'configra_management';
GRANT SELECT ON `configra`.* TO 'configra_backup', 'configra_doctor';
GRANT SELECT ON `configra`.`schema_migrations` TO 'configra_gc';
GRANT SELECT ON `configra`.`operations` TO 'configra_gc';
GRANT SELECT ON `configra`.`outbox_events` TO 'configra_gc';
GRANT SELECT ON `configra`.`notification_targets` TO 'configra_gc';
GRANT SELECT ON `configra`.`notification_deliveries` TO 'configra_gc';
GRANT INSERT ON `configra`.`operations` TO 'configra_gc';
GRANT INSERT ON `configra`.`outbox_events` TO 'configra_gc';
GRANT UPDATE ON `configra`.`operations` TO 'configra_gc';
GRANT DELETE ON `configra`.`outbox_events` TO 'configra_gc';
GRANT DELETE ON `configra`.`notification_targets` TO 'configra_gc';
GRANT DELETE ON `configra`.`notification_deliveries` TO 'configra_gc';
-- MySQL 8.0.22 role-based locking reads require an additional write privilege.
-- Restrict that privilege to the Sentinel identity column (never encrypted bytes).
GRANT UPDATE(id) ON `configra`.`crypto_sentinel` TO 'configra_api', 'configra_management';
