apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: configra-provider
resources:
  - daemonset.yaml
images:
  - name: configra-kubernetes
    newName: registry.example.com/configra-kubernetes
    newTag: v0.1.0
