apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: configra-api
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: configra
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: configra-management
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: configra
      app.kubernetes.io/component: management
