apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: configra
resources:
  - ../base
  - disruption-budgets.yaml
  - network-policy.yaml
patches:
  - path: workloads.yaml
  - path: config.yaml
  - path: services.yaml
